### PR TITLE
iD Support (and other stuff)

### LINKED ISSUE #11: iD Support
macrocosm should work with a minimally-modified version of iD.

### PR DESCRIPTION
**Pull request by sethfitz**
This changes endpoints (and implements new ones) necessary to support the iD editor.

Of the changes, the `map` endpoint is probably the most significant, as it changes up the queries that fetch features (matching [cgimap](http://wiki.openstreetmap.org/wiki/Cgimap), the OSM C++ implementation of the `map` endpoint). Previously, nodes that were not part of ways were not being returned.

Fixes #11

/cc @olafveerman @dereklieu @danielfdsilva @kamicut

### CODE REVIEW

**Comment by dereklieu** [comment]
Hey @mojodna, first off thanks for all the work here! 

I've done some work off your branch. My goals were to preserve compatibility with original routes in addition to iD/OSM routes (`api/0.6` route syntax), modify tests to pass with the new code and make fixes where applicable, and update the docker testing environment to run on node 5.3.

The code is on a [new branch](https://github.com/developmentseed/macrocosm/tree/pr12-merge-enhancements). Could you review and fast-forward into your branch if it still accomplishes your goals?

My other request is to please provide documentation and simple test coverage for the additional endpoints you've added, to cover possible future regressions. I'm seeing these:

`/api/0.6/nodes`
`/api/0.6/ways`
`/api/capabilities`
`/api/user`

We use [apidocjs](http://apidocjs.com/). Happy to help as much as I can with both documentation and test coverage.

**Comment by sethfitz** [comment]
Sweet. I think I'll have time to incorporate your changes later in the week and then we'll be on the same path once again.

**Comment by dereklieu** [comment]
@mojodna great. I'll hold off on merging these changes until you do.

**Comment by sethfitz** [comment]
@dereklieu Fast-forwarded, etc, but I haven't written docs / tests just yet. That's next.

**Comment by sethfitz** [comment]
(And I'm seeing a bunch of test failures locally, so I want to sort those out before this gets merged.)

**Comment by dereklieu** [comment]
@mojodna Cool. Let me know if you have any questions regarding any of the tests.

**Comment by sethfitz** [comment]
Existing tests pass now (locally). API docs are next.

**Comment by sethfitz** [comment]
@dereklieu this is ready to merge from my POV.

I haven't added new tests, but I'm willing to deal with breakage and introduce them when that happens. I'll also be adding some additional functionality (user info, history info in the db to be able to walk changesets) that will probably touch each of the endpoints I added, so I'll add tests at that point. (I'd like to get us synced up sooner rather than later.)

**Comment by dereklieu** [comment]
Thanks @mojodna. The new feature list is minimal at this point, so I'm ok to sync up now and write tests for those later. Can't wait to see the new features/tests you write for that additional functionality.

I've spotted some minor fixes, which I'll open a PR for after I merge this. I'll also be doing some work to make sure `/upload` works again, so watch out for a PR.

**Pull request merged**
